### ISSUE TITLE
Background Auto-Join & Hiding DLC do not work

### ISSUE THREAD

**Issue by Hennihenner** [ge-ku/AutoJoin-for-SteamGifts#17]
Hey there.

I've recently got a new HDD because of severe computer issues, previously auto join in background worked perfectly. Now, it doesn't, the extension isn't even running in the background (Enabled in SG settings, chrome settings; other background extensions work) and I can't find a fix for it.

Additionally, hiding DLC giveaways does not work at all (doubt this one is solveable on my side)

**Comment by ge-ku** [comment]
Hello, Please open chrome://extensions/ and enable Developer mode (top of the page), then disable and enable extension and click on "Inspect views: background page". It should open a window with console, wait for about a minute after enabling extension and paste or screenshot output here.

I'll check hiding DLC issue later.

**Comment by Hennihenner** [comment]
![2017-09-07 18_17_54-developer tools - chrome-extension___bchhlccjhoedhhegglilngpbnldfcidc__generated](https://user-images.githubusercontent.com/19843204/30173713-f33de73a-93f8-11e7-8be4-c46cf735e8c4.png)

Says i have 0pts, i got 37

**Comment by ge-ku** [comment]
Hiding DLC is [now fixed](https://github.com/ge-ku/AutoJoin-for-SteamGifts/commit/ca6199751aff528dc3c0c318401ecf2c92bde11d) (not yet in Chrome Store). Thanks for noticing it!

As for this other issue, I'm not sure why it thinks you have 0 points when you have more.
Can you open developer console (Ctrl + Shift + J) on steamgifts.com and paste there `jQuery('a[href="/account"]').find("span.nav__points").text()` It should retrieve amount of points same way it does in the background.

**Comment by Hennihenner** [comment]
gives me "2424" while having 24pts

**Comment by ge-ku** [comment]
This is even weirder! Can you do the same but paste `jQuery('a[href="/account"]').html()`?

**Comment by Hennihenner** [comment]
`"Account (<span class="nav__points">24</span>P / <span title="4.00">Level 4</span>)"`

**Comment by ge-ku** [comment]
Seems fine, now why doesn't it return the same in background is a question... Can you link me your Steam profile so we communicate faster?

**Comment by Hennihenner** [comment]
http://steamcommunity.com/id/hennihenner/
