### ISSUE TITLE
[Feature Request] Precise time remaining

### ISSUE THREAD

**Issue by DraxxorT** [ge-ku/AutoJoin-for-SteamGifts#23]
I'd really like it if the "X [days/hours/minutes] remaining" note was more precise. I know you can hover over it to see the precise time the giveaway ends, but it would be nice if it just displayed a more accurate countdown there. Whether it's static on page load or dynamic and counts down doesn't matter to me. I'd just rather see 0:01:26:34 than simply "1 hour," because truncating that (nearly) half hour makes a difference in the giveaways I might enter, now that the point distribution is fixed.

**Comment by vaibhavhrt** [comment]
should be possible to do that, I will look into it.

**Comment by ge-ku** [comment]
Thanks to @vaibhavhrt this is now available as an option (disabled by default).
