### ISSUE TITLE
AutoJoin every in minutes

### ISSUE THREAD

**Issue by S0ulHunt3r** [ge-ku/AutoJoin-for-SteamGifts#3]
Hi there, great job doing this plugin, i only have one sugestion about AutoJoin, and that is to give the possibility of the retry being in minutes.

**Comment by ge-ku** [comment]
Hi, is there a reason for this? I don't think you can regain all your points in under an hour.

**Comment by S0ulHunt3r** [comment]
When you have a high volume of games, like now :) because of the high game value of humble bundle.

**Comment by ge-ku** [comment]
I made it so you can set it to 0.5 hour, I hope it's enough :)

**Comment by S0ulHunt3r** [comment]
Roger that, thanks
