### ISSUE TITLE
[Feature request] Option to remind user about checking SteamGifts

### ISSUE THREAD

**Issue by HiddenKn** [ge-ku/AutoJoin-for-SteamGifts#30]
Since there is now a chance you can get banned when you automatically use the website, would it be possible to instead (not saying you should remove the existing feature though) remind the user to check the page whenever they have more than X points and/or a certain amount of time has passed?

**Comment by ge-ku** [comment]
That's a cool idea, [just added](https://github.com/ge-ku/AutoJoin-for-SteamGifts/commit/0e77b36f993c546dfcb06855ca99375eee4bd5a1) an option to notify when certain amount of points is reached. No setting for time passed though, so it will notify each 30 minutes until points are spent. Setting is disabled by default so make sure you enable it and tell me if you notice anything wrong with it.

**Comment by HiddenKn** [comment]
Seems to work fine to me.
