### ISSUE TITLE
[Feature request] Add the option to hide giveaways above X level

### ISSUE THREAD

**Issue by igwi** [ge-ku/AutoJoin-for-SteamGifts#33]
This would be really useful, and I am not sure why show giveaways I'm not allowed to join.
Similar to the setting "HideLevelsBelow".

**Comment by ge-ku** [comment]
This is already a feature of Steamgifts itself. Go to [steamgifts.com/account/settings/giveaways](https://www.steamgifts.com/account/settings/giveaways) and set "Hide giveaways above your level?" to "Yes".
