### ISSUE TITLE
Notification link

### ISSUE THREAD

**Issue by OdarGM** [ge-ku/AutoJoin-for-SteamGifts#38]
Everyday when i have 400 points or more it sends me a notifcation about it but when i click the notification it doesn't open the site can you make it to do that? 💯

**Comment by ge-ku** [comment]
Hello, it should open steamgifts main page already, does clicking on winning notification work?

**Comment by OdarGM** [comment]
clicking on winning works

**Comment by ge-ku** [comment]
Strange, both notification types use same logic (just different URLs, `https://www.steamgifts.com/giveaways/won` for winning and `https://www.steamgifts.com/` for points).

Can you please open extension page (`chrome://extensions/?id=bchhlccjhoedhhegglilngpbnldfcidc`), enable developer mode (top right corner) and click on "background page", this will open a small console window. Now into this window enter `notify('points', 333)`, notification should pop up, click on it and tell me what happens (new tab opens or you get some kind of message in this console window).

**Comment by OdarGM** [comment]
The notications is showing but the link is still not working ;-;

![gif](http://media.odar.xyz/x2L67FJ9d6.gif)

**Comment by ge-ku** [comment]
I didn't realise that Chrome finally uses native Windows 10 notifications! So I tested it on Windows 10 and.. it still works on my end. I've no idea why it doesn't in your case, can you perhaps try updating Chrome (judging by older UI you're not on latest version).
