### ISSUE TITLE
[Feature request] Hide regional restricted giveaways

### ISSUE THREAD

**Issue by DonSleza4e** [ge-ku/AutoJoin-for-SteamGifts#39]
Could you add option to hide giveaways with region restriction?

Currently website offers me to join giveaways even if my country is not in "allowed" list. And I never saw a region restricted giveaway with my country in list. So I would like to hide them at all.

**Comment by ge-ku** [comment]
You should simply contact SG support to change your country (you can see which on is currently set on this page [https://www.steamgifts.com/account/settings/profile](https://www.steamgifts.com/account/settings/profile)): 

> The above country should be the region used by your Steam account. It is important you select the correct country, as it will allow you to enter region restricted giveaways available to you. If it needs to be changed, please contact support.

**Comment by DonSleza4e** [comment]
Thank you, got it
