### ISSUE TITLE
Can't save the settings

### ISSUE THREAD

**Issue by MurkBRA** [ge-ku/AutoJoin-for-SteamGifts#4]
Hi, like me and some ppl have noticed that settings can't be change/save.

**Comment by ge-ku** [comment]
Hi, I can't reproduce it, saves fine for me. Is there an error message in console when you're trying to save?

**Comment by MurkBRA** [comment]
No error in console but I can save some settings like infinite scroll and others. The real problem is with "autojoin background" time can't be save, "delay between requests" can't be save and "Try to AutoJoin in background every" can't be save.

**Comment by ge-ku** [comment]
This is strange, it saves those values for me just fine. I have no idea how to fix it for you because I don't know what causes it.

**Comment by MurkBRA** [comment]
I did with a new profile and again don't save.
I'm on win7 x64 with [slimjet 12.0.14.0 (64-bit)](http://www.slimjet.com/pt/postdl.php?version=win64&type=exe) and [vivaldi 1.6.689.40 x64](https://downloads.vivaldi.com/stable/Vivaldi.1.6.689.40.x64.exe)
Maybe this is the problem?

**Comment by ge-ku** [comment]
Can't say for sure, I tested it with Chrome only. Just asked a friend if it saves for him and he says it does (he's also using Chrome).

**Comment by ge-ku** [comment]
Just tried in Vivaldi, works fine for me there, sorry I can't help you.

**Comment by MurkBRA** [comment]
Ok, you know where chrome store this settings?

**Comment by ge-ku** [comment]
You can view stored settings if you enable developer mode, then open "background page" under autojoin extension in chrome://extensions/ and enter `chrome.storage.sync.get(null, function (data) { console.info(data) });`
If you want to save anything this way enter `chrome.storage.sync.set({RepeatHoursBG:"1"});`
P.S. If you want to set RepeatHoursBG to 0.5 you should set it to 0.

**Comment by MurkBRA** [comment]
Thank you, seems all fine now.
I have this userscript that I did and you could test him and say what you think. I did changes on button settings and msg of autojoin, nighttheme mixed with some needed css to make sidebar scroll follow work, blacklist, giveaways with copies highlight.
The code is a bit messy but it works.
http://pastebin.com/x2aNrAFW

**Comment by ge-ku** [comment]
Sorry it took me some time, I like it, especially sidebar and top bar being always visible!
