### ISSUE TITLE
join/ leave not showing

### ISSUE THREAD

**Issue by erka15** [ge-ku/AutoJoin-for-SteamGifts#45]
only first giveaway has join/leave button but other giveaway has not
edit:  Infinite Scrolling s also not working

https://imgur.com/6R05WPO
[https://imgur.com/6R05WPO](url)

I only use Infinite Scrolling and Show buttons to join/leave on settings

Google Chrome
Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by ge-ku** [comment]
Both seem to work fine on my end, same Chrome version. Try opening console (Ctrl+Shift+J) and see if there are any related errors (besides failed attempts to get data from Steam).

**Comment by erka15** [comment]
cdn.steamgifts.com/js/prebid_v9.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
c.amazon-adsystem.com/aax2/apstag.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
integrator.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
integrator.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
search?region_restricted=true&entry_max=99000:1 Access to XMLHttpRequest at 'https://steamcommunity.com/profiles/********************/wishlist' from origin 'https://www.steamgifts.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
autoentry.js:174 Uncaught TypeError: Cannot read property 'dataset' of null
    at autoentry.js:174
    at NodeList.forEach (<anonymous>)
    at modifyPageDOM (autoentry.js:127)
    at onPageLoad (autoentry.js:622)
    at XMLHttpRequest.wishxhr.onreadystatechange (autoentry.js:341)
steamcommunity.com/profiles/***************/wishlist:1 Failed to load resource: net::ERR_FAILED
search?region_restricted=true&entry_max=99000:1 Access to XMLHttpRequest at 'https://steamcommunity.com/profiles/*****************/games/?tab=all' from origin 'https://www.steamgifts.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
steamcommunity.com/profiles/***************/games/?tab=all:1 Failed to load resource: net::ERR_FAILED
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map

**Comment by ge-ku** [comment]
I see, for some reason your page is missing hiding icons (extension assumes they are always present for each giveaway).

![image](https://user-images.githubusercontent.com/11873225/75852781-67ea4b00-5df5-11ea-9541-f9719c3c3c49.png)

Did you filter it out with adblock perhaps or some Steamgifts setting (I couldn't find one)?

**Comment by erka15** [comment]
> I see, for some reason your page is missing hiding icons (extension assumes they are always present for each giveaway).
> 
> ![image](https://user-images.githubusercontent.com/11873225/75852781-67ea4b00-5df5-11ea-9541-f9719c3c3c49.png)
> 
> Did you filter it out with adblock perhaps or some Steamgifts setting (I couldn't find one)?

yeup. 20k games re hidden

**Comment by ge-ku** [comment]
I just uploaded new version to Chrome Web Store (1.8.0) that doesn't break when giveaway has no Hide button. It should be published soon.
