### ISSUE TITLE
More Giveaways Page (magnifying glass icon) not working with extension

### ISSUE THREAD

**Issue by bsadov** [ge-ku/AutoJoin-for-SteamGifts#61]
On the main page there is a 'more giveaways' option to filter and only show you giveaways of that specific game. Looks like steamgifts made some changes to that page, making it incompatible with the extension. Settings like infinite scrolling, and the join/leave buttons do not appear anymore.

**Comment by ge-ku** [comment]
Hey, thanks for your changes! I [decided to add those "/game/*" pages to manifest](https://github.com/ge-ku/AutoJoin-for-SteamGifts/commit/3a3bb2575fe1314c38ccb20f4b0d3d84d7d060ea), it should work now without replacing URL.

**Comment by bsadov** [comment]
Thank you for fixing it up; updating the manifest is definitely the cleanest. I originally tried that but it was my first time editing an extension so I definitely missed something along the way. Good learning experience either way
