### ISSUE TITLE
[Feature Request] Random comment

### ISSUE THREAD

**Issue by Lucas83** [ge-ku/AutoJoin-for-SteamGifts#65]
My idea is to make the application select a random comment from configuration panel. Comments could be written divided by a semicolon like:

`thanks;thank you very much;nice;great!`

With option to randomly select one of these comments. And with one interesting option. If I could leave empty spaces like this:

`;;thanks;thank you very much`

Then there should be 2 chances for 4, to application would leave no comment.

**Comment by SariusGH** [comment]
I think this would be a good addition and created a PR with a possible implementation.

I also changed the separating symbol from ";" to "#" as this allows the usage of comments including smiles like ";)".

**Comment by ge-ku** [comment]
@SariusGH thanks for your pull requests! I just merged both of them (this one and hiding above a certain level and point cost). Uploaded to Firefox add-ons and Chrome store as version 1.9.6, should update there soon.
