### ISSUE TITLE
Auto join on background not working anymore since yesterday

### ISSUE THREAD

**Issue by TioHell** [ge-ku/AutoJoin-for-SteamGifts#68]
As the tittle says, the auto join is not working anymore

**Comment by ge-ku** [comment]
Hello, I just uploaded new version (1.10.1), please try again once your extension is updated and tell me if it works.

**Comment by TioHell** [comment]
> Hello, I just uploaded new version (1.10.1), please try again once your extension is updated and tell me if it works.

hi, sorry about the delay, i waited 24h after the extension got updated to see if it would change something, so yeah, nothing, is still nothing auto joining on background, even after the update

**Comment by ge-ku** [comment]
It works on my end, can't reproduce for now.

Can you please open extension page.
Extensions > Manage Extensions > Click "details" on AutoJoin or paste this into address bar ```chrome://extensions/?id=bchhlccjhoedhhegglilngpbnldfcidc```

Turn on developer mode (top right corner).

Then you'll see "Inspect views
service worker
html/offscreen.html"

Open both of these and see if there are any errors and send it here if you see any. Thanks.

**Comment by TioHell** [comment]
> It works on my end, can't reproduce for now.
> 
> Can you please open extension page. Extensions > Manage Extensions > Click "details" on AutoJoin or paste this into address bar `chrome://extensions/?id=bchhlccjhoedhhegglilngpbnldfcidc`
> 
> Turn on developer mode (top right corner).
> 
> Then you'll see "Inspect views service worker html/offscreen.html"
> 
> Open both of these and see if there are any errors and send it here if you see any. Thanks.

hi, i was going to reinstall the extension but saw a "error" button on the auto join, i think it may be the reason
![2024-08-22_185257](https://github.com/user-attachments/assets/52bb669f-35dd-407f-9cda-24b5305ff380)

**Comment by ge-ku** [comment]
Thanks. Hopefully new update will fix it, I *think* it was breaking trying to parse a page that had no giveaways on it (for example if your settings are joining wishlist giveaways and load 2 pages but there's only 1 page at the moment).
New version number is 1.10.2, once it reaches you, can take some time.

Please let me know if it works then.

**Comment by TioHell** [comment]
> Thanks. Hopefully new update will fix it, I _think_ it was breaking trying to parse a page that had no giveaways on it (for example if your settings are joining wishlist giveaways and load 2 pages but there's only 1 page at the moment). New version number is 1.10.2, once it reaches you, can take some time.
> 
> Please let me know if it works then.

Hi, i just got the update, couldn't test yet if is working or not, but letting you know some new errors showed
![2024-08-22_212845](https://github.com/user-attachments/assets/009a6d78-e376-4501-96a8-f2a2e1a1dfda)

**Comment by TioHell** [comment]
> Thanks. Hopefully new update will fix it, I _think_ it was breaking trying to parse a page that had no giveaways on it (for example if your settings are joining wishlist giveaways and load 2 pages but there's only 1 page at the moment). New version number is 1.10.2, once it reaches you, can take some time.
> 
> Please let me know if it works then.

hi, the auto join on background is working again, thanks for the help :)
