### ISSUE TITLE
Auto join on background not working again :(

### ISSUE THREAD

**Issue by TioHell** [ge-ku/AutoJoin-for-SteamGifts#69]
Hi, after the 1.10.2 update the auto join on background worked for a few hours, now its not working again and some new errors are showing on chrome 
![2024-08-24_182934](https://github.com/user-attachments/assets/80246938-7550-4518-af5c-50dfc9ef00b0)

**Comment by ge-ku** [comment]
Hi, first error on your screenshot should be fixed in the new update (1.10.3), are other errors new or from before?

**Comment by ge-ku** [comment]
Oh, I think I figured it out, it can throw error if there is no permissions to access steamcommunity.com but some option which uses it is enabled. Will try to fix it and disable these options if we don't have needed permissions granted.

**Comment by ge-ku** [comment]
Version 1.10.4 should fix those errors, let me know if it works once update arrives.

**Comment by ge-ku** [comment]
> any prediction for the release date of the new update? There is some weeks that it doesn't work in background for me

Latest version is in Chrome store and should work right now, if it doesn't:

Include your settings and check if there are any errors when you go to extension page (Extensions > Manage Extensions > Details or paste chrome://extensions/?id=bchhlccjhoedhhegglilngpbnldfcidc into address bar). Enable Developer mode in top right corner.

You'll then see:
**Inspect views**
_**service worker
html/offscreen.html**_

Click on both of these and if you see errors, send them.

**Comment by jdvb123** [comment]
![image](https://github.com/user-attachments/assets/3089e5a2-18d4-4aaf-98fa-1c338a2f9d07)
![image](https://github.com/user-attachments/assets/e63884db-ba20-4a74-a5de-596273f0b25c)

**Comment by jdvb123** [comment]
beside the "error" i've read in the options mentioned, the extention now are working fine again! Thx very much, i'm using it since 2016 and your extention helped me a lot!!

**Comment by TioHell** [comment]
Sorry about the huge delay, had to make sure everything was working, and it is, thanks for all the help :)

**Comment by ge-ku** [comment]
> ![image](https://private-user-images.githubusercontent.com/128835151/362424756-3089e5a2-18d4-4aaf-98fa-1c338a2f9d07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTA5MzUsIm5iZiI6MTcyNDkxMDYzNSwicGF0aCI6Ii8xMjg4MzUxNTEvMzYyNDI0NzU2LTMwODllNWEyLTE4ZDQtNGFhZi05OGZhLTFjMzM4YTJmOWQwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTUwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjFkNDI2MTM5NTFkYjgzNGUyOTU0MDlkNjBjZDA4YjI1NmJkNzNhYjdjYWU2Y2QxY2M5NTg5OTk2NzdmZjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B7obgcKyTXE-_sPyuKJ09GZ5Wjz9Lvl1yUioYyyT1PM) ![image](https://private-user-images.githubusercontent.com/128835151/362424983-e63884db-ba20-4a74-a5de-596273f0b25c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTA5MzUsIm5iZiI6MTcyNDkxMDYzNSwicGF0aCI6Ii8xMjg4MzUxNTEvMzYyNDI0OTgzLWU2Mzg4NGRiLWJhMjAtNGE3NC1hNWRlLTU5NjI3M2YwYjI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTUwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWU1YjM5M2M2MmY1YmIxNWMzYzg2MGM5YmQ2ZTEyMDYyZWI1NjdlZjUxMWM4Yzg3YjA0YTNlOGRkMzA1NmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ufSoOc7baEljuyH74r3y3lqJTRa8R1V3j9W0KReEUUU)

I couldn't figure out when this error may appear, new version (1.10.5) was uploaded that added additional log messages in this case, once update arrives and you get this error again, it should also print more lines, please share them (you can open a new issue).

**Comment by jdvb123** [comment]
unfortunately it isn't working for me yet

**Comment by ge-ku** [comment]
> unfortunately it isn't working for me yet

Can you please check for errors again? If it's the same error, it should print more information now, which will help me find what causes it.

**Comment by jdvb123** [comment]
It doesn't have any error tho, i don't know what's happening but it doesn't work in background annymore, i've reinstalled the extension and nothing

I have this message but don't know if this is something to care about:
![Sem título](https://github.com/user-attachments/assets/f1767112-15bf-42ac-8166-62e632159762)

**Comment by jdvb123** [comment]
everything's fine with my configs too 
![Sem título](https://github.com/user-attachments/assets/1dd6d8ab-572f-4dda-a487-586f8db2c5ac)

**Comment by jdvb123** [comment]
![image](https://github.com/user-attachments/assets/2ed80f26-80f3-42f9-aea8-07b75b1a2dc7)
found this

**Comment by ge-ku** [comment]
"inactive" is fine when it's waiting for the next cycle. Those warnings should not matter but I'll fix them. And what about Console tab? Is there anything, even if not errors? "Alarm fired" messages at least should be there every hour.

**Comment by jdvb123** [comment]
There's absolutely nothing in the "console" page, not a single word

**Comment by jdvb123** [comment]
![image](https://github.com/user-attachments/assets/f1b4c808-abce-4ab3-b4c1-61f3d22c2dee)

**Comment by ge-ku** [comment]
@jdvb123 just uploaded new version (1.10.6) that should fix all those warning messages. But I also tried installing current version in Edge with your settings and while it gives these same warnings there, it also works fine, there's an "Alarm fired" message in console and everything else as in Chrome. So I don't think it'll fix your issue, I'm not sure what's causing it.

Is it possible for you to try again in Chrome, just to see if it works there?

**Comment by jdvb123** [comment]
Tested in Chrome, didn't work aswell (only firefox works)
Another detail (i don't think that's important but idk) is that after clicking the autojoin button it works, but in Edge/Chrome there's no "Good Luck" message, in firefox it works like before and it shows the message.. strange, i'm using this tool since 2018 and it's the first time this happens, it always worked fine in background, but now there's always 400 points and no giveaways joined, unless i click the button :/

**Comment by jdvb123** [comment]
Is there any way to make the older updates available to download? They were working fine for me

**Comment by ge-ku** [comment]
> Is there any way to make the older updates available to download? They were working fine for me

This whole update was because of Chrome [dropping manifest v2 support soon](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline), it will stop working at some point, extension was updated to use manifest v3. Firefox doesn't plan to drop manifest v2 support, so I didn't update it there for now.

You can try to download version 1.9.6 from https://github.com/ge-ku/AutoJoin-for-SteamGifts/tree/57392e13da4643eec8f0af208abff4c380bca9e7 (click Code => Download ZIP), unpack it and [install as unpacked extension](https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked).

This way you can use it until manifest v2 is disabled. But I'd like to find the cause of this issue and make new version work.
Can you try opening Steamgifts website and see if there's anything in the console (Ctrl+Shift+J) related to extension?

**Comment by jdvb123** [comment]
After reloading and cleaning cache: 
![image](https://github.com/user-attachments/assets/1d973b8b-50ad-42ce-b3f4-b6c736162d0d)

**Comment by ge-ku** [comment]
These errors are not coming from extension (they will likely be there if you disable it completely), messages about caching and hiding are from extension, but they seem fine. I still can't understand why it doesn't work in the background or at least output an error that we could trace, sorry.

**Comment by jdvb123** [comment]
So strange, other people are with the same problems or there's something wrong here? I even installed Chrome from zero and tested the extention there with the same configs for a whole day and nothing :/

**Comment by ge-ku** [comment]
Not that I'm aware of, there were some errors initially (like the start of this issue) but those were much easier to track down.
I uploaded new version (1.10.7) where I tried creating recurring alarms in a different way and with a bit of additional logging, once you get it please:

- go to chrome://extensions/?id=bniebidmjdhakadjcdepeannooebanjj
- disable and enable extension
- click on "service worker"

see if it prints anything out this time, if it prints "alarm set", wait for 30 seconds and see if more messages appear.

**Comment by jdvb123** [comment]
Installed the old version and it works again. 
I've installed the new version now and apparently it's fixed!
![image](https://github.com/user-attachments/assets/46bd459f-4bce-4505-8c64-7598c86604d5)

**Comment by ge-ku** [comment]
Great! I still don't understand why it didn’t work previously, but I’m glad that it’s fixed now.
