### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by PaulCombal** [ge-ku/AutoJoin-for-SteamGifts#9]
Hi again,
I first started to contribute to this project to add the "Ignore featured giveaways" options, I just had to do it because entering shit giveaways and manually leaving them was very irritating. Now contributing to this project taught me the basics of a chrome browser extension, and helped me review my very basic jQuery skills. That being said, I'll probably stop contributing to this project as I do not think there is much left to do as of right now.

Before leaving, I wanted to ask for the permission to create a wiki for this project, in order to help new contributor where to start.

Thanks for everything :)

**Comment by ge-ku** [comment]
Sure, that'll be great.

I'm right now in the middle of remaking settings (you could see that in one of my latest commits, it doesn't work right now as it should). So maybe start creating it a bit later, when it all works :) I'll leave a message here.

**Comment by ge-ku** [comment]
Okay, I guess I'm done with that. There's now 3 identical chunks of code in 3 separate files. But I plan to remove those when majority people receive update. Can you please test it before I upload it into Chrome store? On background page you can call `loadOldFormatSettings()` to load a set of old settings and `showSettings()` to get all settings stored currently. I tested it myself opening steamgifts.com, opening settings page and waiting for new alarm from background page and they all seem to convert old settings to new, but just to make sure...

**Comment by PaulCombal** [comment]
Just tried that on WIndows, looks like it's working just fine. Worst case scenario some users will have to reset their settings, so it's no big deal really I guess.

Don't forget to change the Wiki edition settings!

Thanks a lot for creating this extension by the way, really good work, and good idea!

**Comment by ge-ku** [comment]
Done! And thank you for contributing :)
